# Generated by Django 5.0.6 on 2024-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_location_iframe_location_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcost',
            name='distance',
            field=models.CharField(blank=True, default='---', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locationcost',
            name='time',
            field=models.CharField(blank=True, default='---', max_length=200, null=True),
        ),
    ]
